/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_liuyifeng_hellojni_MainActivity */

#ifndef _Included_com_demo_liuyifeng_hellojni_MainActivity
#define _Included_com_demo_liuyifeng_hellojni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_liuyifeng_hellojni_MainActivity
 * Method:    hellojni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_demo_liuyifeng_hellojni_MainActivity_hellojni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
